#!/usr/bin/env perl

use v5.10;

use FindBin;
use lib "$FindBin::Bin/../kubernetes-builder/lib/";

use strict;
use warnings;
use KubeBuilder;

$|=1;

my $builder = KubeBuilder->new(
  schema_file => 'spec/swagger.json'
);

foreach my $o_name (sort keys %{ $builder->objects }){
  my $object = $builder->objects->{ $o_name };
  $builder->log->info("Generating object for definition $o_name");
  $builder->process_template(
    'object',
    { object => $object },
  );
}

