package IO::K8s::Api::Events::V1beta1::Event;
  use Moose;

  has 'deprecatedLastTimestamp' => (is => 'ro', isa => 'IO::K8s::Apimachinery::Pkg::Apis::Meta::V1::Time'  );
  has 'series' => (is => 'ro', isa => 'IO::K8s::Api::Events::V1beta1::EventSeries'  );
  has 'reportingController' => (is => 'ro', isa => 'Str'  );
  has 'reason' => (is => 'ro', isa => 'Str'  );
  has 'eventTime' => (is => 'ro', isa => 'IO::K8s::Apimachinery::Pkg::Apis::Meta::V1::MicroTime'  );
  has 'kind' => (is => 'ro', isa => 'Str'  );
  has 'type' => (is => 'ro', isa => 'Str'  );
  has 'regarding' => (is => 'ro', isa => 'IO::K8s::Api::Core::V1::ObjectReference'  );
  has 'reportingInstance' => (is => 'ro', isa => 'Str'  );
  has 'deprecatedCount' => (is => 'ro', isa => 'Int'  );
  has 'related' => (is => 'ro', isa => 'IO::K8s::Api::Core::V1::ObjectReference'  );
  has 'action' => (is => 'ro', isa => 'Str'  );
  has 'metadata' => (is => 'ro', isa => 'IO::K8s::Apimachinery::Pkg::Apis::Meta::V1::ObjectMeta'  );
  has 'note' => (is => 'ro', isa => 'Str'  );
  has 'deprecatedFirstTimestamp' => (is => 'ro', isa => 'IO::K8s::Apimachinery::Pkg::Apis::Meta::V1::Time'  );
  has 'deprecatedSource' => (is => 'ro', isa => 'IO::K8s::Api::Core::V1::EventSource'  );
  has 'apiVersion' => (is => 'ro', isa => 'Str'  );
1;
