package IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaProps;
  use Moose;

  has '$schema' => (is => 'ro', isa => 'Str'  );
  has 'not' => (is => 'ro', isa => 'IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaProps'  );
  has 'default' => (is => 'ro', isa => 'IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSON'  );
  has 'minItems' => (is => 'ro', isa => 'Int'  );
  has 'maxItems' => (is => 'ro', isa => 'Int'  );
  has 'definitions' => (is => 'ro', isa => 'HashRef[IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaProps]'  );
  has 'type' => (is => 'ro', isa => 'Str'  );
  has 'minLength' => (is => 'ro', isa => 'Int'  );
  has 'title' => (is => 'ro', isa => 'Str'  );
  has 'minProperties' => (is => 'ro', isa => 'Int'  );
  has 'maximum' => (is => 'ro', isa => 'Num'  );
  has 'format' => (is => 'ro', isa => 'Str'  );
  has 'patternProperties' => (is => 'ro', isa => 'HashRef[IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaProps]'  );
  has 'anyOf' => (is => 'ro', isa => 'ArrayRef[IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaProps]'  );
  has 'oneOf' => (is => 'ro', isa => 'ArrayRef[IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaProps]'  );
  has 'dependencies' => (is => 'ro', isa => 'HashRef[IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaPropsOrStringArray]'  );
  has 'multipleOf' => (is => 'ro', isa => 'Num'  );
  has 'maxLength' => (is => 'ro', isa => 'Int'  );
  has 'additionalProperties' => (is => 'ro', isa => 'IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaPropsOrBool'  );
  has 'exclusiveMinimum' => (is => 'ro', isa => 'Bool'  );
  has '$ref' => (is => 'ro', isa => 'Str'  );
  has 'enum' => (is => 'ro', isa => 'ArrayRef[IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSON]'  );
  has 'externalDocs' => (is => 'ro', isa => 'IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::ExternalDocumentation'  );
  has 'minimum' => (is => 'ro', isa => 'Num'  );
  has 'allOf' => (is => 'ro', isa => 'ArrayRef[IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaProps]'  );
  has 'pattern' => (is => 'ro', isa => 'Str'  );
  has 'items' => (is => 'ro', isa => 'IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaPropsOrArray'  );
  has 'uniqueItems' => (is => 'ro', isa => 'Bool'  );
  has 'id' => (is => 'ro', isa => 'Str'  );
  has 'maxProperties' => (is => 'ro', isa => 'Int'  );
  has 'example' => (is => 'ro', isa => 'IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSON'  );
  has 'exclusiveMaximum' => (is => 'ro', isa => 'Bool'  );
  has 'additionalItems' => (is => 'ro', isa => 'IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaPropsOrBool'  );
  has 'description' => (is => 'ro', isa => 'Str'  );
  has 'required' => (is => 'ro', isa => 'ArrayRef[Str]'  );
  has 'properties' => (is => 'ro', isa => 'HashRef[IO::K8s::ApiExtensionsApiServer::Pkg::Apis::Apiextensions::V1beta1::JSONSchemaProps]'  );
1;
